### ISSUE TITLE
Mod isn't showing in mod menu

### ISSUE THREAD

**Issue by MyMajorJohnson** [Voland163/TFTV#6]
I have the GOG version: Phoenix Point: Complete Edition – v1.20.1 installed. Mod menu is showing but nothing is in the mod menu. Mod is installed in root directory under /Mods folder. Does this mod work with Modnix or Phoenix Point Mod Loader? I haven't installed either.
Thanks.

![Phoenix Point Screenshot](https://github.com/Voland163/TFTV/assets/169266296/2b4c89f1-f3d6-4778-9de4-2161f1472585)

**Comment by jarnomikkola1** [comment]
You cannot "install" the mod, you extract the downloaded TFTV.zip file, that has a TestMod folder, is that folder in the Mods folder, or did you extract it into a "TFTV" folder ? That's made due to the file name usually.
Removing either one of those folders, from between, doesn't matter which, should make the mod appear into the MODS menu. 
Aka the mods primary file, called TFTV.dll should be in ... Phoenix Point/Mods/TestMod/TFTV.dll -location. 
And you aren't the first, nor only person that has had this problem.

**Comment by MyMajorJohnson** [comment]
Hi, thanks for a quick response. It was installed under /Mods/TFTV-v.1.1.0.1 folder. I figured it out by removing the "TFTV-v.1.1.0.1" folder. I don't have in TestMod folder. All the files are now in the Phoenix Point/Mods folder and it seems to be working. I see the splash title screen.

First time playing this game. Not sure why you include the "TFTV-v.1.1.0.1" main folder in the .zip? I assumed it was just copy paste into /Mods folder. Anyway thanks.
