### ISSUE TITLE
ppdefmodifier

### ISSUE THREAD

**Issue by babut85** [Voland163/TFTV#9]
i want to be able not to follow the misconception of the authors of this mod that the new takes away the right to life for the old, but only adds variability. for example, gaussian technologies have high armor penetration, but lower damage, laser technologies burn armor, but do not penetrate it. well, and the like, which has at least some connection with reality, and not the stereotypical nonsense that absolutely all game developers follow. and for that, i need ppdefmodifier(i've already done definition files for it before), but i can't find a way to connect it

**Comment by jarnomikkola1** [comment]
You would get far more help by going into the Discord server and there asking help, rather than making an issue about a thing the mod doesn't even touch. 
The PPDefModifier doesn't work with the PPME/Steam Workshop mods. 

You can join the discord server here; https://discord.gg/SUH8UgWEde -it's the permanent invite. 
.. by making a free discord profile and then I would suggest to going to the "off-topic" text thread and there, ask help.
